[project]
name = "scrape-flights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fast-flights>=2.2",
    "fastapi>=0.128.0",
    "ipython>=9.9.0",
    "uvicorn>=0.40.0",
]
